In [1]:
import numpy as np
import pandas as pd

In [3]:
movies_df=pd.read_csv('tmdb_5000_movies.csv')
credits_df=pd.read_csv('tmdb_5000_credits.csv')

In [7]:
movies_df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [9]:
credits_df

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
df=movies_df.merge(credits_df,on='title')         # merging both the data frames

In [17]:
df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

### remove columns that are not needed (finally we need columns that can give us tags)

In [20]:
# needed columns = Genre,id, keywords, title (in english),overview,cast, crew. 
# As the Target was to create tags, mostly all the
# numerical columns are dropped and those columns have been kept which can help in creating tags

In [22]:
df=df[['movie_id','title','overview','keywords','cast','crew','genres']]

In [23]:
df

,movie_id,title,overview,keywords,cast,crew,genres
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""id"": 99, ""name"": ""Documentary""}]"

In [25]:
df.isna().sum()

movie_id    0
title       0
overview    3
keywords    0
cast        0
crew        0
genres      0
dtype: int64

In [26]:
df=df.dropna()

In [30]:
df.duplicated().sum()

0

In [52]:
type(df['genres'][0])

str

In [56]:
# As these are strings of list of dictionaries we need to convert it to list

In [57]:
a = eval(df['genres'][0])  
print(a)

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]

In [58]:
a[0]

{'id': 28, 'name': 'Action'}

In [60]:
a[0]['name']

'Action'

In [63]:
def find_name(input):
    L=[]
    for i in eval(input):
        L.append(i['name'])
    return L

In [65]:
df['genres']=df['genres'].apply(find_name)

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\3005967486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(find_name)

In [66]:
df

,movie_id,title,overview,keywords,cast,crew,genres
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Action, Adventure, Fantasy, Science Fiction]"
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Adventure, Fantasy, Action]"
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[Action, Adventure, Science Fiction]"
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[Action, Crime, Thriller]"
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...","[Comedy, Romance]"
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[Comedy, Drama, Romance, TV Movie]"
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",[Documentary]

In [67]:
def find_top3_name(input):
    L=[]
    counter=0
    for i in eval(input):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [68]:
df['cast']=df['cast'].apply(find_top3_name)

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\1689839699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast']=df['cast'].apply(find_top3_name)

In [70]:
df['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [71]:
df['keywords']=df['keywords'].apply(find_name)

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\2197093746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(find_name)

In [73]:
df['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [74]:
def find_dir(input):
    L=[]
    for i in eval(input):
        if i['job']=='Director':
            L.append(i['name'])
    return L

In [76]:
df['crew']=df['crew'].apply(find_dir)

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\2146299233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew']=df['crew'].apply(find_dir)

In [77]:
df

,movie_id,title,overview,keywords,cast,crew,genres
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Action, Adventure, Fantasy, Science Fiction]"
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Adventure, Fantasy, Action]"
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],"[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[Action, Adventure, Science Fiction]"
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],"[Action, Crime, Thriller]"
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",[Edward Burns],"[Comedy, Romance]"
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],"[Comedy, Drama, Romance, TV Movie]"
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],[]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]",[Documentary]

In [78]:
df['overview']=df['overview'].apply(lambda x:x.split())

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\572531931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview']=df['overview'].apply(lambda x:x.split())

In [79]:
df

,movie_id,title,overview,keywords,cast,crew,genres
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Action, Adventure, Fantasy, Science Fiction]"
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Adventure, Fantasy, Action]"
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],"[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[Action, Adventure, Science Fiction]"
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],"[Action, Crime, Thriller]"
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",[Edward Burns],"[Comedy, Romance]"
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],"[Comedy, Drama, Romance, TV Movie]"
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],[]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]",[Documentary]

In [81]:
#Having Blaank spaces in such a case is not recommended so we need to remove the blank spaces from all the columns

In [84]:
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df['crew']=df['crew'].apply(lambda x:[i.replace(" ","") for i in x])
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\4006664886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\4006664886.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\4006664886.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew']=df['crew'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\4006664886.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [86]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\3111474342.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']

In [87]:
df.head()

,movie_id,title,overview,keywords,cast,crew,genres,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [88]:
df_final=df[['movie_id','title','tags']]

In [89]:
df_final

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [90]:
#join all the tags with spaces

In [91]:
df_final['tags']=df_final['tags'].apply(lambda x:" ".join(x))

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\361293405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['tags']=df_final['tags'].apply(lambda x:" ".join(x))

In [92]:
df_final

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [93]:
df_final['tags']=df_final['tags'].apply(lambda x:x.lower())

C:\Users\mrchi\AppData\Local\Temp\ipykernel_7332\3331091921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['tags']=df_final['tags'].apply(lambda x:x.lower())

In [94]:
df_final

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [138]:
df_final['movie_id'][df_final['title'].loc[df_final['title']=='El Mariachi'].index[0]]

9367

In [95]:
#using CountVecctorizer make all the tags as vectors

In [99]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vector_of_tags=cv.fit_transform(df_final['tags']).toarray()

In [102]:
vector_of_tags.shape

(4806, 5000)

In [103]:
from sklearn.metrics.pairwise import cosine_similarity

In [104]:
similarity=cosine_similarity(vector_of_tags)

In [106]:
similarity.shape

(4806, 4806)

In [196]:
distances= sorted(list(enumerate(similarity[2])),reverse=True,key =lambda x:x[1])

In [197]:
distances

[(2, 0.9999999999999998),
 (11, 0.37387825055298296),
 (1346, 0.3507392801587168),
 (29, 0.30179727289671415),
 (3166, 0.2813874297663251),
 (4077, 0.278243337456101),
 (3340, 0.23947373603569985),
 (4343, 0.2357831326780108),
 (1723, 0.2351585405008862),
 (147, 0.23346307108777453),
 (1134, 0.22953904252438354),
 (1749, 0.21561438627179408),
 (277, 0.21044356809523007),
 (3255, 0.19634744970862505),
 (3289, 0.18725147156828456),
 (1843, 0.18330889377669166),
 (1719, 0.18215302221567486),
 (134, 0.1796053020267749),
 (4010, 0.1796053020267749),
 (4641, 0.1796053020267749),
 (1087, 0.17960530202677488),
 (3355, 0.1771615786072478),
 (170, 0.17108830085824553),
 (1775, 0.17108830085824553),
 (1203, 0.169525817893769),
 (227, 0.16395645894598823),
 (282, 0.16395645894598823),
 (1103, 0.1636783307407345),
 (972, 0.16129032258064518),
 (1537, 0.16129032258064518),
 (7, 0.1606438657804998),
 (2680, 0.1606438657804998),
 (939, 0.15839698777049716),
 (105, 0.1531679162134967),
 (1886, 0.1531679162134967),
 (973, 0.15179418517972906),
 (698, 0.15089863644835705),
 (1085, 0.14980117725462766),
 (2753, 0.14980117725462766),
 (3347, 0.1496710850223124),
 (2999, 0.14944064441601537),
 (1080, 0.14763464883937316),
 (695, 0.14664711502135333),
 (1513, 0.14664711502135333),
 (2364, 0.1466471150213533),
 (1592, 0.1437993271357627),
 (372, 0.1419904585617662),
 (711, 0.1408939907352694),
 (3356, 0.1408939907352694),
 (1369, 0.1402481783633036),
 (2332, 0.13912166872805048),
 (76, 0.13856849886842332),
 (23, 0.1382602259640567),
 (17, 0.13685937700384793),
 (4148, 0.13576884666042613),
 (708, 0.13538259026847058),
 (218, 0.13470397652008118),
 (1621, 0.13470397652008118),
 (3407, 0.13386988815041648),
 (164, 0.13340746919301402),
 (1523, 0.13340746919301402),
 (3263, 0.13340746919301402),
 (2056, 0.13240678533309402),
 (50, 0.13116516715679058),
 (1004, 0.13116516715679058),
 (62, 0.13068205256070964),
 (205, 0.13068205256070964),
 (256, 0.13068205256070964),
 (808, 0.13068205256070964),
 (2558, 0.13068205256070964),
 (88, 0.12903225806451615),
 (108, 0.12828950144769635),
 (596, 0.12828950144769635),
 (1445, 0.12828950144769635),
 (3147, 0.12789136689584626),
 (166, 0.1270001270001905),
 (180, 0.1270001270001905),
 (241, 0.1270001270001905),
 (1237, 0.1270001270001905),
 (1703, 0.1270001270001905),
 (3721, 0.1270001270001905),
 (4406, 0.1270001270001905),
 (58, 0.1257488637069642),
 (1284, 0.1252721535988985),
 (46, 0.1250610798961445),
 (753, 0.1250610798961445),
 (1727, 0.12361284651454937),
 (1676, 0.12335342787286213),
 (2404, 0.12335342787286213),
 (437, 0.12320822072673948),
 (508, 0.12320822072673948),
 (3235, 0.12320822072673948),
 (207, 0.12143534814378325),
 (3498, 0.12143534814378325),
 (252, 0.12108986992412071),
 (179, 0.12048289933537483),
 (267, 0.12048289933537483),
 (418, 0.12048289933537483),
 (1721, 0.12048289933537483),
 (3863, 0.12048289933537483),
 (3975, 0.12048289933537483),
 (188, 0.12000384018432986),
 (187, 0.11973686801784994),
 (370, 0.11973686801784994),
 (987, 0.11973686801784994),
 (329, 0.11810771907149853),
 (2683, 0.11810771907149853),
 (1154, 0.11757927025044308),
 (1194, 0.11757927025044308),
 (1670, 0.11757927025044308),
 (2925, 0.11757927025044308),
 (3055, 0.11757927025044308),
 (2086, 0.11691309338623894),
 (36, 0.116543309349613),
 (210, 0.116543309349613),
 (350, 0.116543309349613),
 (988, 0.116543309349613),
 (1250, 0.116543309349613),
 (1367, 0.11503946170861017),
 (2008, 0.11503946170861017),
 (139, 0.1149805124545685),
 (56, 0.11487593716012254),
 (249, 0.11487593716012254),
 (498, 0.11487593716012254),
 (2937, 0.11487593716012254),
 (2962, 0.11487593716012254),
 (4623, 0.11487593716012254),
 (1648, 0.11359236684941297),
 (2007, 0.11359236684941297),
 (2080, 0.11359236684941297),
 (3229, 0.11359236684941297),
 (3595, 0.11359236684941297),
 (3614, 0.11359236684941297),
 (3720, 0.11359236684941297),
 (4488, 0.11359236684941297),
 (263, 0.11235088294097074),
 (466, 0.11235088294097074),
 (590, 0.11235088294097074),
 (783, 0.11235088294097074),
 (2919, 0.11235088294097074),
 (129, 0.11219854269064289),
 (1086, 0.11219854269064289),
 (2395, 0.11219854269064289),
 (4015, 0.11174521339154048),
 (190, 0.11138647983852826),
 (724, 0.11085479909473867),
 (952, 0.11085479909473867),
 (2052, 0.11085479909473867),
 (400, 0.10998533626601499),
 (1092, 0.10998533626601499),
 (371, 0.10955820713295535),
 (683, 0.10955820713295535),
 (3184, 0.10955820713295535),
 (1276, 0.10830607221477648),
 (3025, 0.10830607221477648),
 (4071, 0.10830607221477648),
 (2650, 0.10830607221477646),
 (292, 0.10776318121606496),
 (691, 0.10776318121606496),
 (2741, 0.10776318121606496),
 (531, 0.1070959105203332),
 (831, 0.1070959105203332),
 (2752, 0.1070959105203332),
 (1798, 0.10592542826647522),
 (1938, 0.10592542826647522),
 (219, 0.10567049305145204),
 (367, 0.10567049305145204),
 (1076, 0.10567049305145204),
 (1259, 0.10567049305145204),
 (1365, 0.10567049305145204),
 (2283, 0.10567049305145204),
 (2652, 0.10567049305145204),
 (483, 0.10369516947304254),
 (1275, 0.10369516947304254),
 (1444, 0.10369516947304254),
 (4405, 0.10369516947304254),
 (152, 0.10182663499531959),
 (511, 0.10182663499531959),
 (794, 0.10182663499531959),
 (1027, 0.10182663499531959),
 (1431, 0.10182663499531959),
 (2206, 0.10182663499531959),
 (4781, 0.10182663499531959),
 (248, 0.10059909096557137),
 (425, 0.10059909096557136),
 (2153, 0.10059909096557136),
 (2162, 0.10059909096557136),
 (3739, 0.10040241611281236),
 (28, 0.10005560189476051),
 (260, 0.10005560189476051),
 (392, 0.10005560189476051),
 (678, 0.10005560189476051),
 (840, 0.10005560189476051),
 (1079, 0.10005560189476051),
 (2817, 0.10005560189476051),
 (3264, 0.10005560189476051),
 (3438, 0.10005560189476051),
 (3890, 0.10005560189476051),
 (4468, 0.10005560189476051),
 (314, 0.09962709627734359),
 (1673, 0.09962709627734359),
 (2274, 0.09962709627734359),
 (2480, 0.09962709627734359),
 (3978, 0.09962709627734359),
 (4261, 0.09962709627734359),
 (4348, 0.09962709627734359),
 (4502, 0.09962709627734359),
 (183, 0.0991704379697524),
 (2598, 0.0986827422982897),
 (72, 0.09837387536759294),
 (128, 0.09837387536759294),
 (356, 0.09837387536759294),
 (369, 0.09837387536759294),
 (402, 0.09837387536759294),
 (700, 0.09837387536759294),
 (1364, 0.09837387536759294),
 (1667, 0.09837387536759294),
 (2865, 0.09837387536759294),
 (3322, 0.09837387536759294),
 (354, 0.09776474334756886),
 (777, 0.09776474334756886),
 (1305, 0.09776474334756886),
 (1456, 0.09776474334756886),
 (2005, 0.09776474334756886),
 (121, 0.09677419354838711),
 (245, 0.09677419354838711),
 (468, 0.09677419354838711),
 (512, 0.09677419354838711),
 (544, 0.09677419354838711),
 (1485, 0.09677419354838711),
 (1746, 0.09677419354838711),
 (3301, 0.09677419354838711),
 (3845, 0.09677419354838711),
 (1104, 0.09600307214746387),
 (1879, 0.09600307214746387),
 (3363, 0.09600307214746387),
 (3733, 0.09600307214746387),
 (3854, 0.09600307214746387),
 (294, 0.09525009525014287),
 (514, 0.09525009525014287),
 (859, 0.09525009525014287),
 (1616, 0.09525009525014287),
 (2984, 0.09525009525014287),
 (654, 0.0951572136139613),
 (10, 0.09379580992210838),
 (741, 0.09379580992210838),
 (2202, 0.09379580992210838),
 (3428, 0.09379580992210838),
 (4162, 0.09353047470899116),
 (403, 0.09353047470899115),
 (4048, 0.09353047470899115),
 (1139, 0.09274777915203365),
 (1437, 0.09274777915203365),
 (2061, 0.09274777915203365),
 (2173, 0.09274777915203365),
 (3731, 0.09274777915203365),
 (568, 0.09240616554505461),
 (746, 0.09240616554505461),
 (1548, 0.09240616554505461),
 (1739, 0.09240616554505461),
 (2211, 0.09240616554505461),
 (2243, 0.09240616554505461),
 (2686, 0.09240616554505461),
 (3140, 0.09240616554505461),
 (3310, 0.09240616554505461),
 (3526, 0.09240616554505461),
 (3557, 0.09240616554505461),
 (4078, 0.09240616554505461),
 (47, 0.0919844099636548),
 (1898, 0.0919844099636548),
 (51, 0.09123958466923195),
 (1641, 0.09123958466923195),
 (26, 0.09107651110783743),
 (332, 0.09107651110783743),
 (339, 0.09107651110783743),
 (1195, 0.09107651110783743),
 (1220, 0.09107651110783743),
 (1380, 0.09107651110783743),
 (2013, 0.09107651110783743),
 (2450, 0.09107651110783743),
 (3169, 0.09107651110783743),
 (3805, 0.09107651110783743),
 (3855, 0.09107651110783743),
 (4770, 0.09107651110783743),
 (40, 0.08980265101338746),
 (131, 0.08980265101338746),
 (208, 0.08980265101338746),
 (291, 0.08980265101338746),
 (330, 0.08980265101338746),
 (534, 0.08980265101338746),
 (858, 0.08980265101338746),
 (866, 0.08980265101338746),
 (1401, 0.08980265101338746),
 (1758, 0.08980265101338746),
 (1943, 0.08980265101338746),
 (2352, 0.08980265101338746),
 (2780, 0.08980265101338746),
 (2885, 0.08980265101338746),
 (3243, 0.08980265101338746),
 (3303, 0.08980265101338746),
 (3496, 0.08980265101338746),
 (3527, 0.08980265101338746),
 (3620, 0.08980265101338746),
 (4131, 0.08980265101338746),
 (38, 0.0891091838708226),
 (755, 0.0891091838708226),
 (82, 0.0885807893036239),
 (223, 0.0885807893036239),
 (503, 0.0885807893036239),
 (594, 0.0885807893036239),
 (1511, 0.0885807893036239),
 (1602, 0.0885807893036239),
 (1921, 0.0885807893036239),
 (4098, 0.0885807893036239),
 (677, 0.08740748201220976),
 (731, 0.08740748201220976),
 (1015, 0.08740748201220976),
 (1061, 0.08740748201220976),
 (1273, 0.08740748201220976),
 (2823, 0.08740748201220976),
 (3152, 0.08740748201220976),
 (151, 0.08712136837380642),
 (1323, 0.08712136837380642),
 (1464, 0.08712136837380642),
 (1613, 0.08712136837380642),
 (2297, 0.08712136837380642),
 (2882, 0.08712136837380642),
 (3420, 0.08712136837380642),
 (3918, 0.08712136837380642),
 (4231, 0.08712136837380642),
 (4568, 0.08712136837380642),
 (163, 0.08627959628145762),
 (659, 0.08627959628145762),
 (1204, 0.08627959628145762),
 (1297, 0.08627959628145762),
 (1299, 0.08627959628145762),
 (2180, 0.08627959628145762),
 (2527, 0.08627959628145762),
 (3401, 0.08627959628145762),
 (3704, 0.08627959628145762),
 (78, 0.08519427513705972),
 (182, 0.08519427513705972),
 (930, 0.08519427513705972),
 (1109, 0.08519427513705972),
 (1733, 0.08519427513705972),
 (1900, 0.08519427513705972),
 (2377, 0.08519427513705972),
 (3675, 0.08519427513705972),
 (109, 0.08466675133346034),
 (800, 0.08466675133346034),
 (1476, 0.08466675133346034),
 (2335, 0.08466675133346034),
 (2390, 0.08466675133346034),
 (2394, 0.08466675133346034),
 (2935, 0.08466675133346034),
 (3077, 0.08466675133346034),
 (3141, 0.08466675133346034),
 (3730, 0.08466675133346034),
 (3832, 0.08466675133346034),
 (4412, 0.08466675133346034),
 (788, 0.08414890701798217),
 (1127, 0.08414890701798217),
 (2014, 0.08414890701798217),
 (2934, 0.08414890701798217),
 (4045, 0.08414890701798217),
 (4425, 0.08414890701798217),
 (4795, 0.08414890701798217),
 (4, 0.083141099321054),
 (394, 0.083141099321054),
 (523, 0.083141099321054),
 (543, 0.083141099321054),
 (2916, 0.083141099321054),
 (4083, 0.083141099321054),
 (2354, 0.08314109932105399),
 (342, 0.08295613557843401),
 (127, 0.08240856434303291),
 (160, 0.08240856434303291),
 (200, 0.08240856434303291),
 (627, 0.08240856434303291),
 (739, 0.08240856434303291),
 (995, 0.08240856434303291),
 (1026, 0.08240856434303291),
 (2323, 0.08240856434303291),
 (2385, 0.08240856434303291),
 (3627, 0.08240856434303291),
 (3972, 0.08240856434303291),
 (3982, 0.08240856434303291),
 (4082, 0.08240856434303291),
 (270, 0.08216865534971651),
 (640, 0.08216865534971651),
 (870, 0.08216865534971651),
 (1471, 0.08216865534971651),
 (2095, 0.08216865534971651),
 (3458, 0.08216865534971651),
 (140, 0.08122955416108235),
 (158, 0.08122955416108235),
 (419, 0.08122955416108235),
 (782, 0.08122955416108235),
 (933, 0.08122955416108235),
 (963, 0.08122955416108235),
 (1003, 0.08122955416108235),
 (1186, 0.08122955416108235),
 (1281, 0.08122955416108235),
 (1583, 0.08122955416108235),
 (2713, 0.08122955416108235),
 (228, 0.0803219328902499),
 (580, 0.0803219328902499),
 (767, 0.0803219328902499),
 (1285, 0.0803219328902499),
 (1823, 0.0803219328902499),
 (490, 0.08032193289024989),
 (613, 0.08032193289024989),
 (751, 0.08032193289024989),
 (1174, 0.08032193289024989),
 (1544, 0.08032193289024989),
 (1634, 0.08032193289024989),
 (2117, 0.08032193289024989),
 (2244, 0.08032193289024989),
 (3081, 0.08032193289024989),
 (3261, 0.08032193289024989),
 (3663, 0.08032193289024989),
 (4099, 0.08032193289024989),
 (4135, 0.08032193289024989),
 (97, 0.07944407119985641),
 (262, 0.07944407119985641),
 (665, 0.07944407119985641),
 (735, 0.07944407119985641),
 (3039, 0.07944407119985641),
 (4105, 0.07944407119985641),
 (2448, 0.07933635037580192),
 (83, 0.07859437755933692),
 (215, 0.07859437755933692),
 (273, 0.07859437755933692),
 (1814, 0.07859437755933692),
 (2596, 0.07859437755933692),
 (4334, 0.07859437755933692),
 (4529, 0.07859437755933692),
 (35, 0.07838618016696206),
 (162, 0.07838618016696206),
 (325, 0.07838618016696206),
 (561, 0.07838618016696206),
 (773, 0.07838618016696206),
 (924, 0.07838618016696206),
 (1044, 0.07838618016696206),
 (1166, 0.07838618016696206),
 (1438, 0.07838618016696206),
 (1681, 0.07838618016696206),
 (2342, 0.07838618016696206),
 (2463, 0.07838618016696206),
 (2521, 0.07838618016696206),
 (2980, 0.07838618016696206),
 (3089, 0.07838618016696206),
 (3336, 0.07838618016696206),
 (3352, 0.07838618016696206),
 (3590, 0.07838618016696206),
 (4290, 0.07838618016696206),
 (30, 0.07777137710478191),
 (119, 0.07777137710478191),
 (123, 0.07777137710478191),
 (574, 0.07777137710478191),
 (702, 0.07777137710478191),
 (1463, 0.07777137710478191),
 (2049, 0.07702283825049334),
 (2301, 0.07702283825049334),
 (3377, 0.07702283825049334),
 (386, 0.07697370086861781),
 (600, 0.07697370086861781),
 (1140, 0.07697370086861781),
 (1864, 0.07697370086861781),
 (3341, 0.07697370086861781),
 (3740, 0.07697370086861781),
 (61, 0.07658395810674835),
 (233, 0.07658395810674835),
 (304, 0.07658395810674835),
 (495, 0.07658395810674835),
 (914, 0.07658395810674835),
 (1049, 0.07658395810674835),
 (1226, 0.07658395810674835),
 (1410, 0.07658395810674835),
 (1787, 0.07658395810674835),
 (2078, 0.07658395810674835),
 (2508, 0.07658395810674835),
 (2564, 0.07658395810674835),
 (2584, 0.07658395810674835),
 (2762, 0.07658395810674835),
 (3133, 0.07658395810674835),
 (3374, 0.07658395810674835),
 (3395, 0.07658395810674835),
 (3558, 0.07658395810674835),
 (3839, 0.07658395810674835),
 (3999, 0.07658395810674835),
 (169, 0.0762000762001143),
 (2135, 0.0762000762001143),
 (3330, 0.0762000762001143),
 (5, 0.07544931822417852),
 (694, 0.07544931822417852),
 (747, 0.07544931822417852),
 (1155, 0.07544931822417852),
 (3508, 0.07544931822417852),
 (33, 0.07490058862731383),
 (157, 0.07490058862731383),
 (237, 0.07490058862731383),
 (308, 0.07490058862731383),
 (715, 0.07490058862731383),
 (1055, 0.07490058862731383),
 (1242, 0.07490058862731383),
 (1301, 0.07490058862731383),
 (1327, 0.07490058862731383),
 (1329, 0.07490058862731383),
 (1423, 0.07490058862731383),
 (1494, 0.07490058862731383),
 (2067, 0.07490058862731383),
 (2228, 0.07490058862731383),
 (3297, 0.07490058862731383),
 (3621, 0.07490058862731383),
 (4285, 0.07490058862731383),
 (4320, 0.07490058862731383),
 (4357, 0.07490058862731383),
 (4476, 0.07490058862731383),
 (469, 0.07472032220800769),
 (873, 0.07472032220800769),
 (1396, 0.07472032220800769),
 (2133, 0.07472032220800769),
 (2541, 0.07472032220800769),
 (673, 0.07401205672371727),
 (1030, 0.07401205672371727),
 (69, 0.07370846071967477),
 (167, 0.07332355751067667),
 (201, 0.07332355751067667),
 (202, 0.07332355751067667),
 (247, 0.07332355751067667),
 (660, 0.07332355751067667),
 (781, 0.07332355751067667),
 (1562, 0.07332355751067667),
 (1833, 0.07332355751067667),
 (1860, 0.07332355751067667),
 (1973, 0.07332355751067667),
 (2496, 0.07332355751067667),
 (2579, 0.07332355751067667),
 (2661, 0.07332355751067667),
 (3046, 0.07332355751067667),
 (3421, 0.07332355751067667),
 (4216, 0.07332355751067667),
 (2256, 0.07332355751067665),
 (3000, 0.07332355751067665),
 (285, 0.07265392195447243),
 (1462, 0.07265392195447243),
 (1992, 0.07265392195447243),
 (2498, 0.07265392195447243),
 (2603, 0.07265392195447243),
 (2804, 0.07265392195447243),
 (985, 0.072571501142966),
 (573, 0.07200230411059791),
 (2439, 0.07200230411059791),
 (3732, 0.07200230411059791),
 (290, 0.07184212081070997),
 (389, 0.07184212081070997),
 (530, 0.07184212081070997),
 (604, 0.07184212081070997),
 (920, 0.07184212081070997),
 (1016, 0.07184212081070997),
 (1077, 0.07184212081070997),
 (1158, 0.07184212081070997),
 (1177, 0.07184212081070997),
 (1570, 0.07184212081070997),
 (1579, 0.07184212081070997),
 (1631, 0.07184212081070997),
 (1964, 0.07184212081070997),
 (2501, 0.07184212081070997),
 (2651, 0.07184212081070997),
 (2957, 0.07184212081070997),
 (3110, 0.07184212081070997),
 (3148, 0.07184212081070997),
 (3467, 0.07184212081070997),
 (3968, 0.07184212081070997),
 (4355, 0.07184212081070997),
 (4509, 0.07184212081070997),
 (969, 0.07136791021047098),
 (1282, 0.07136791021047098),
 (2106, 0.07136791021047098),
 (2760, 0.07136791021047098),
 (103, 0.07074999459548673),
 (1878, 0.07074999459548673),
 (3361, 0.07074999459548673),
 (68, 0.0704469953676347),
 (94, 0.0704469953676347),
 (433, 0.0704469953676347),
 (615, 0.0704469953676347),
 (721, 0.0704469953676347),
 (791, 0.0704469953676347),
 (976, 0.0704469953676347),
 (1047, 0.0704469953676347),
 (1096, 0.0704469953676347),
 (1363, 0.0704469953676347),
 (1589, 0.0704469953676347),
 (1658, 0.0704469953676347),
 (1756, 0.0704469953676347),
 (2120, 0.0704469953676347),
 (2227, 0.0704469953676347),
 (2231, 0.0704469953676347),
 (2378, 0.0704469953676347),
 (2396, 0.0704469953676347),
 (2588, 0.0704469953676347),
 (2615, 0.0704469953676347),
 (3376, 0.0704469953676347),
 (3692, 0.0704469953676347),
 (3770, 0.0704469953676347),
 (3834, 0.0704469953676347),
 (3857, 0.0704469953676347),
 (4141, 0.0704469953676347),
 (4196, 0.0704469953676347),
 (4667, 0.0704469953676347),
 (253, 0.07014785603174337),
 (155, 0.06956083436402524),
 (213, 0.06956083436402524),
 (142, 0.06913011298202835),
 (216, 0.06913011298202835),
 (384, 0.06913011298202835),
 (581, 0.06913011298202835),
 (664, 0.06913011298202835),
 (762, 0.06913011298202835),
 (941, 0.06913011298202835),
 (1052, 0.06913011298202835),
 (1427, 0.06913011298202835),
 (1492, 0.06913011298202835),
 (1596, 0.06913011298202835),
 (2348, 0.06913011298202835),
 (2538, 0.06913011298202835),
 (2786, 0.06913011298202835),
 (3277, 0.06913011298202835),
 (3362, 0.06913011298202835),
 (3435, 0.06913011298202835),
 (3780, 0.06913011298202835),
 (4775, 0.06913011298202835),
 (153, 0.0689883074727411),
 (696, 0.0689883074727411),
 (1678, 0.0689883074727411),
 (1361, 0.06842968850192396),
 (3862, 0.06842968850192396),
 (8, 0.06788442333021306),
 (12, 0.06788442333021306),
 (31, 0.06788442333021306),
 (91, 0.06788442333021306),
 (122, 0.06788442333021306),
 (259, 0.06788442333021306),
 (922, 0.06788442333021306),
 (931, 0.06788442333021306),
 (1181, 0.06788442333021306),
 (1306, 0.06788442333021306),
 (1425, 0.06788442333021306),
 (1440, 0.06788442333021306),
 (1469, 0.06788442333021306),
 (1854, 0.06788442333021306),
 (1926, 0.06788442333021306),
 (2235, 0.06788442333021306),
 (2507, 0.06788442333021306),
 (2795, 0.06788442333021306),
 (2840, 0.06788442333021306),
 (3238, 0.06788442333021306),
 (3353, 0.06788442333021306),
 (3530, 0.06788442333021306),
 (3766, 0.06788442333021306),
 (3913, 0.06788442333021306),
 (4505, 0.06788442333021306),
 (65, 0.06683188790311695),
 (150, 0.06683188790311695),
 (1541, 0.06683188790311695),
 (2539, 0.06683188790311695),
 (4429, 0.06683188790311695),
 (21, 0.06670373459650701),
 (242, 0.06670373459650701),
 (745, 0.06670373459650701),
 (960, 0.06670373459650701),
 (977, 0.06670373459650701),
 (1001, 0.06670373459650701),
 (1149, 0.06670373459650701),
 (1453, 0.06670373459650701),
 (1726, 0.06670373459650701),
 (1903, 0.06670373459650701),
 (2022, 0.06670373459650701),

In [199]:
for i in distances[1:6]:
    print(df_final.iloc[i[0]].title)

Quantum of Solace
Never Say Never Again
Skyfall
Thunderball
From Russia with Love

In [201]:
def recommend_movie(input_movie_name):
    input_movie_id=df_final[df_final['title']==input_movie_name].index[0]
    distances= sorted(list(enumerate(similarity[input_movie_id])),reverse=True,key =lambda x:x[1])    
    for i in distances[1:6]:
        print(df_final.iloc[i[0]].title)

In [202]:
recommend_movie('The Dark Knight Rises')

The Dark Knight
Batman Begins
Batman
Batman Returns
Batman